openapi: 3.0.3
info:
  title: Schedule OpenAPI definition
  version: 1.0.11
servers:
  - url: https://localhost:8080
paths:
  /year/{yearId}:
    get:
      summary: Fetch plan for the whole year
      description: Fetch plan for the whole year of UG IP
      operationId: getScheduleForSpecificYear
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'          
        '400':
          description: Invalid ID supplied
        '404':
          description: Schedule not found

  /year/{yearId}/group/{groupId}:
    get:
      summary: Fetch plan for the specific group
      description: Fetch plan for the specific group of UG IP
      operationId: getScheduleForGroup
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        '400':
          description: Invalid ID supplied
        '404':
          description: Schedule not found
  
components:
  schemas:
    Schedule:
      type: object